# Generated by Django 6.0.1 on 2026-02-20 16:00

import UTrade_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=UTrade_app.models.user_profile_path, verbose_name='Profile Picture'),
        ),
    ]
