# Generated by Django 6.0.1 on 2026-05-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedvariant',
            name='variant_attribute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
