# Generated by Django 6.0 on 2026-01-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Rating'),
        ),
    ]
