# Generated by Django 6.0.1 on 2026-03-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
