# Generated by Django 6.0.1 on 2026-08-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0002_stagedvariant_variant_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meetup_locations',
        ),
        migrations.AddField(
            model_name='product',
            name='meetup_location_text',
            field=models.CharField(blank=True, help_text='Preferred campus meetup spot', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_meetup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagedproduct',
            name='preferred_meetup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagedproduct',
            name='meetup_locations_list',
            field=models.CharField(blank=True, help_text='Single campus meetup location', max_length=255),
        ),
    ]
