# Generated by Django 6.0.1 on 2026-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0002_servicesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
