# Generated by Django 6.0.1 on 2026-01-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0002_alter_user_user_number_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
