# Generated by Django 6.0.1 on 2026-03-27 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0003_productimage_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='assigned_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_variants', to='UTrade_app.productimage'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(max_length=100),
        ),
    ]
