# Generated by Django 6.0.1 on 2026-02-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0003_services_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesimage',
            old_name='product',
            new_name='service',
        ),
    ]
