# Generated by Django 6.0.1 on 2026-08-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0003_remove_product_meetup_locations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='preferred_meetup_time',
            new_name='preferred_meetup_time_from',
        ),
        migrations.RenameField(
            model_name='stagedproduct',
            old_name='preferred_meetup_time',
            new_name='preferred_meetup_time_from',
        ),
        migrations.AddField(
            model_name='product',
            name='available_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_meetup_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagedproduct',
            name='available_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stagedproduct',
            name='preferred_meetup_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
