# Generated by Django 6.0.1 on 2026-09-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0004_rename_preferred_meetup_time_product_preferred_meetup_time_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Auto code e.g. UTR-2026-0042', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stagedproduct',
            name='product_code',
            field=models.CharField(blank=True, help_text='Auto code e.g. UTR-2026-0042', max_length=32, null=True, unique=True),
        ),
    ]
