# Generated by Django 6.0.1 on 2026-03-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0004_productvariant_assigned_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='condition',
            field=models.CharField(default='Brand New', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='flaws_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
