# Generated by Django 6.0.1 on 2026-01-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0005_category_products_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_categories',
            new_name='product_category',
        ),
        migrations.AddField(
            model_name='products',
            name='product_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=120, verbose_name='Status'),
        ),
    ]
