# Generated by Django 6.0.1 on 2026-04-01 06:40

import UTrade_app.models.user_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0005_productvariant_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cor_file',
            field=models.ImageField(blank=True, null=True, upload_to=UTrade_app.models.user_models.user_profile_path, verbose_name='COR_file'),
        ),
    ]
