# Generated by Django 6.0.1 on 2026-10-04 17:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0007_user_is_suspended_user_suspension_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.RemoveField(
            model_name='services',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='servicesimage',
            name='service',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='gcash_name',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='gcash_number',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='service_fee',
        ),
        migrations.CreateModel(
            name='OrganizationPlatformLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start', models.DateField()),
                ('cycle_due', models.DateField()),
                ('accumulated_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('accumulated_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DUE', 'Due'), ('PAID', 'Paid / Remitted')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledgers', to='UTrade_app.organization')),
            ],
            options={
                'ordering': ['-cycle_start'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFeeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='UTrade_app.organizationplatformledger')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_fee_line', to='UTrade_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformFeeRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('due_date', models.DateField()),
                ('management_rep_name', models.CharField(max_length=120)),
                ('receipt_no', models.CharField(max_length=32, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remittance', to='UTrade_app.organizationplatformledger')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_remittances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='ServicesImage',
        ),
    ]
