# Generated by Django 6.0.1 on 2026-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('alumni', 'Alumni'), ('staff', 'University Staff')], default='student', max_length=20),
        ),
    ]
