# Generated by Django 6.0.1 on 2026-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0008_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location_options',
            field=models.CharField(default='Campus Main Gate', help_text='Comma-separated locations (e.g. Library, Canteen)', max_length=255),
        ),
    ]
