# Generated by Django 6.0.1 on 2026-10-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0009_alter_conversation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approval_letter',
            field=models.ImageField(blank=True, help_text='JPG/PNG only, max 10 MB', null=True, upload_to='org_approval_letters/'),
        ),
    ]
