# Generated by Django 6.0.1 on 2026-10-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0011_chatmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Pending', max_length=10),
        ),
    ]
