# Generated by Django 6.0.1 on 2026-04-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0012_order_meetup_location_order_pickup_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
