# Generated by Django 6.0.1 on 2026-04-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0016_meetuplocation_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location_options',
        ),
        migrations.AddField(
            model_name='product',
            name='meetup_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='UTrade_app.meetuplocation'),
        ),
    ]
