# Generated by Django 6.0.1 on 2026-04-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0019_conversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
