# Generated by Django 6.0.1 on 2026-04-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0020_user_has_agreed_to_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='officer_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='officer_ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='officer_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
