# Generated by Django 6.0.1 on 2026-04-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0021_user_is_officer_user_officer_id_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('system_admin', 'System Admin'), ('campus_admin', 'Campus Admin'), ('org_officer', 'Organization Officer'), ('alumni_assoc', 'Alumni Association'), ('management', 'Management')], default='student', max_length=20),
        ),
    ]
