# Generated by Django 6.0.1 on 2026-04-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0022_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
    ]
