# Generated by Django 6.0.1 on 2026-04-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0025_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accepted_payments',
            field=models.CharField(choices=[('GCASH', 'GCash Only'), ('COP', 'Cash on Pickup Only'), ('BOTH', 'GCash and COP')], default='BOTH', max_length=10),
        ),
    ]
