# Generated by Django 6.0.1 on 2026-04-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0026_product_accepted_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('To_pickup', 'To_pickup'), ('Paid', 'Paid'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
