# Generated by Django 6.0.1 on 2026-04-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('Changed mind', 'Changed my mind'), ('Found better price', 'Found a better price'), ('Accidental order', 'Accidental order'), ('Seller not responding', 'Seller is not responding'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
