# Generated by Django 6.0.1 on 2026-04-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0029_order_cancellation_note_order_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Only required if owner_type is ORGANIZATION', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='owner_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('ORGANIZATION', 'Organization')], default='PERSONAL', max_length=15),
        ),
    ]
