# Generated by Django 6.0.1 on 2026-04-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0030_product_organization_name_product_owner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='product',
            name='related_org',
            field=models.ForeignKey(blank=True, help_text='Select the organization if this is not a personal listing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='UTrade_app.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='org_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='UTrade_app.organization'),
        ),
    ]
