# Generated by Django 6.0.1 on 2026-05-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0032_preorderrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorderrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PREPARING', 'Seller Preparing Item'), ('READY', 'Ready for Pickup'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('ORGANIZATION', 'Organization'), ('MANAGEMENT', 'Management')], default='PERSONAL', max_length=15),
        ),
    ]
