# Generated by Django 6.0.1 on 2026-05-02 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0033_alter_preorderrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pre_order', models.BooleanField(default=False)),
                ('owner_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('ORGANIZATION', 'Organization'), ('MANAGEMENT', 'Management')], default='PERSONAL', max_length=15)),
                ('meetup_locations_list', models.TextField(help_text='Comma-separated list of locations')),
                ('accepted_payments', models.CharField(choices=[('GCASH', 'GCash Only'), ('COP', 'Cash on Pickup Only'), ('BOTH', 'GCash and COP')], default='BOTH', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UTrade_app.category')),
                ('related_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UTrade_app.organization')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StagedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/staged/')),
                ('is_main', models.BooleanField(default=False)),
                ('staged_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='UTrade_app.stagedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='StagedVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stocks', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(default='Brand New', max_length=50)),
                ('flaws', models.TextField(blank=True, null=True)),
                ('image_index', models.IntegerField(blank=True, null=True)),
                ('staged_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='UTrade_app.stagedproduct')),
            ],
        ),
    ]
