# Generated by Django 6.0.1 on 2026-05-03 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTrade_app', '0035_user_is_email_verified_user_otp_code_user_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seller_net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gcash_name', models.CharField(help_text='Registered GCash Name', max_length=100)),
                ('gcash_number', models.CharField(help_text='09XXXXXXXXX', max_length=11)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('processing', 'Withdrawal Initiated'), ('completed', 'Transferred to Seller'), ('rejected', 'Disputed/Hold')], default='pending', max_length=20)),
                ('transfer_proof', models.ImageField(blank=True, null=True, upload_to='payout_receipts/')),
                ('reference_no', models.CharField(blank=True, help_text='GCash Ref No.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='UTrade_app.order')),
                ('processed_by', models.ForeignKey(limit_choices_to={'user_role': 'management'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
